### ISSUE TITLE
Please update the bower package with the new addElement method.

### ISSUE THREAD

**Issue by dejavu1987** [kumailht/responsive-elements#14]
Hey thanks for the plugin. Its great but the bower package has outdated js. Can you please update the bower package with the latest version?
cheers
Anil

**Comment by kumailht** [comment]
I just gave it a try and it seems to be pulling the latest version. Can you confirm the bug?

**Comment by dejavu1987** [comment]
Just gave it a try but I am still getting the older file.. May be its from the server's cache.. lets wait for some time.
Can you try again using new version number at the mean time?

**Comment by kumailht** [comment]
What is the exact install command you're using?

**Comment by dejavu1987** [comment]
bower install responsive-elements
bower cache clean responsive-elements
bower install responsive-elements --force-latest

**Comment by dejavu1987** [comment]
One thing the version is 1.0.1 though the file "responsive-elements.js" is different from the one in the git

**Comment by kumailht** [comment]
Good spot Anil! The tag was indeed out of date, and should be fixed now. Thank you for contributing to the library.

**Comment by dejavu1987** [comment]
No problem. Thanks for updating the tag.
